import { motion } from 'framer-motion';
import { ArrowRight, Play, Sparkles, Star } from 'lucide-react';
import { Button } from '../common/Button';

interface HeroProps {
  onGetStarted: () => void;
  onLogin: () => void;
}

export function Hero({ onGetStarted, onLogin }: HeroProps) {
  return (
    <section className="relative overflow-hidden pt-20 pb-32">
      {/* Animated gradient background */}
      <div className="absolute inset-0 -z-10">
        <div className="absolute top-0 left-1/4 h-96 w-96 rounded-full bg-primary-500/20 blur-3xl animate-float" />
        <div className="absolute top-20 right-1/4 h-96 w-96 rounded-full bg-secondary-500/20 blur-3xl animate-float" style={{ animationDelay: '2s' }} />
        <div className="absolute bottom-0 left-1/3 h-72 w-72 rounded-full bg-accent-500/10 blur-3xl animate-float" style={{ animationDelay: '4s' }} />
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass border border-primary-500/20 text-sm font-medium text-primary-600 dark:text-primary-400 mb-8"
        >
          <Sparkles className="h-4 w-4" />
          <span>Powered by AI · 14 business modules in minutes</span>
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="text-4xl sm:text-5xl lg:text-7xl font-display font-bold tracking-tight text-slate-900 dark:text-white text-balance max-w-4xl mx-auto"
        >
          Build Your Startup in{' '}
          <span className="gradient-text">Minutes</span> with AI
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="mt-6 text-lg sm:text-xl text-slate-600 dark:text-slate-400 max-w-2xl mx-auto text-balance"
        >
          Turn a single idea into a complete, investor-ready business plan. Executive summary, financials, pitch deck, and 11 more modules — all generated by AI.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.3 }}
          className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4"
        >
          <Button size="lg" onClick={onGetStarted} rightIcon={<ArrowRight className="h-5 w-5" />}>
            Start Building Free
          </Button>
          <Button size="lg" variant="outline" onClick={onLogin} leftIcon={<Play className="h-4 w-4" />}>
            Watch Demo
          </Button>
        </motion.div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.4 }}
          className="mt-12 flex items-center justify-center gap-6 text-sm text-slate-500 dark:text-slate-400"
        >
          <div className="flex items-center gap-1">
            <div className="flex">
              {[0, 1, 2, 3, 4].map((i) => (
                <Star key={i} className="h-4 w-4 fill-warning-400 text-warning-400" />
              ))}
            </div>
            <span className="ml-1 font-medium">4.9/5</span>
          </div>
          <div className="hidden sm:block w-px h-4 bg-slate-300 dark:bg-slate-700" />
          <span className="font-medium">12,000+ founders</span>
          <div className="hidden sm:block w-px h-4 bg-slate-300 dark:bg-slate-700" />
          <span className="font-medium">No credit card required</span>
        </motion.div>
      </div>
    </section>
  );
}
